# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sum_pb2 as sum__pb2


class SumServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateRecord = channel.unary_unary(
        '/sum.SumService/CreateRecord',
        request_serializer=sum__pb2.Record.SerializeToString,
        response_deserializer=sum__pb2.RecordResponse.FromString,
        )
    self.UpdateRecord = channel.unary_unary(
        '/sum.SumService/UpdateRecord',
        request_serializer=sum__pb2.Record.SerializeToString,
        response_deserializer=sum__pb2.RecordResponse.FromString,
        )
    self.ReadRecord = channel.unary_unary(
        '/sum.SumService/ReadRecord',
        request_serializer=sum__pb2.ById.SerializeToString,
        response_deserializer=sum__pb2.RecordResponse.FromString,
        )
    self.ListRecords = channel.unary_unary(
        '/sum.SumService/ListRecords',
        request_serializer=sum__pb2.ListRequest.SerializeToString,
        response_deserializer=sum__pb2.RecordListResponse.FromString,
        )
    self.DeleteRecord = channel.unary_unary(
        '/sum.SumService/DeleteRecord',
        request_serializer=sum__pb2.ById.SerializeToString,
        response_deserializer=sum__pb2.RecordResponse.FromString,
        )
    self.FindRecords = channel.unary_unary(
        '/sum.SumService/FindRecords',
        request_serializer=sum__pb2.ByMeta.SerializeToString,
        response_deserializer=sum__pb2.FindResponse.FromString,
        )
    self.CreateOracle = channel.unary_unary(
        '/sum.SumService/CreateOracle',
        request_serializer=sum__pb2.Oracle.SerializeToString,
        response_deserializer=sum__pb2.OracleResponse.FromString,
        )
    self.UpdateOracle = channel.unary_unary(
        '/sum.SumService/UpdateOracle',
        request_serializer=sum__pb2.Oracle.SerializeToString,
        response_deserializer=sum__pb2.OracleResponse.FromString,
        )
    self.ReadOracle = channel.unary_unary(
        '/sum.SumService/ReadOracle',
        request_serializer=sum__pb2.ById.SerializeToString,
        response_deserializer=sum__pb2.OracleResponse.FromString,
        )
    self.ListOracles = channel.unary_unary(
        '/sum.SumService/ListOracles',
        request_serializer=sum__pb2.ListRequest.SerializeToString,
        response_deserializer=sum__pb2.OracleListResponse.FromString,
        )
    self.FindOracle = channel.unary_unary(
        '/sum.SumService/FindOracle',
        request_serializer=sum__pb2.ByName.SerializeToString,
        response_deserializer=sum__pb2.OracleResponse.FromString,
        )
    self.DeleteOracle = channel.unary_unary(
        '/sum.SumService/DeleteOracle',
        request_serializer=sum__pb2.ById.SerializeToString,
        response_deserializer=sum__pb2.OracleResponse.FromString,
        )
    self.Run = channel.unary_unary(
        '/sum.SumService/Run',
        request_serializer=sum__pb2.Call.SerializeToString,
        response_deserializer=sum__pb2.CallResponse.FromString,
        )
    self.Info = channel.unary_unary(
        '/sum.SumService/Info',
        request_serializer=sum__pb2.Empty.SerializeToString,
        response_deserializer=sum__pb2.ServerInfo.FromString,
        )


class SumServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateRecord(self, request, context):
    """vectors CRUD
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListRecords(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindRecords(self, request, context):
    """find a vector given a meta name and value to filter for
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateOracle(self, request, context):
    """oracles CRUD
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOracle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadOracle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListOracles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindOracle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOracle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Run(self, request, context):
    """execute a call to a oracle given its id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Info(self, request, context):
    """get info about the service
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SumServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateRecord': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRecord,
          request_deserializer=sum__pb2.Record.FromString,
          response_serializer=sum__pb2.RecordResponse.SerializeToString,
      ),
      'UpdateRecord': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateRecord,
          request_deserializer=sum__pb2.Record.FromString,
          response_serializer=sum__pb2.RecordResponse.SerializeToString,
      ),
      'ReadRecord': grpc.unary_unary_rpc_method_handler(
          servicer.ReadRecord,
          request_deserializer=sum__pb2.ById.FromString,
          response_serializer=sum__pb2.RecordResponse.SerializeToString,
      ),
      'ListRecords': grpc.unary_unary_rpc_method_handler(
          servicer.ListRecords,
          request_deserializer=sum__pb2.ListRequest.FromString,
          response_serializer=sum__pb2.RecordListResponse.SerializeToString,
      ),
      'DeleteRecord': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRecord,
          request_deserializer=sum__pb2.ById.FromString,
          response_serializer=sum__pb2.RecordResponse.SerializeToString,
      ),
      'FindRecords': grpc.unary_unary_rpc_method_handler(
          servicer.FindRecords,
          request_deserializer=sum__pb2.ByMeta.FromString,
          response_serializer=sum__pb2.FindResponse.SerializeToString,
      ),
      'CreateOracle': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOracle,
          request_deserializer=sum__pb2.Oracle.FromString,
          response_serializer=sum__pb2.OracleResponse.SerializeToString,
      ),
      'UpdateOracle': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOracle,
          request_deserializer=sum__pb2.Oracle.FromString,
          response_serializer=sum__pb2.OracleResponse.SerializeToString,
      ),
      'ReadOracle': grpc.unary_unary_rpc_method_handler(
          servicer.ReadOracle,
          request_deserializer=sum__pb2.ById.FromString,
          response_serializer=sum__pb2.OracleResponse.SerializeToString,
      ),
      'ListOracles': grpc.unary_unary_rpc_method_handler(
          servicer.ListOracles,
          request_deserializer=sum__pb2.ListRequest.FromString,
          response_serializer=sum__pb2.OracleListResponse.SerializeToString,
      ),
      'FindOracle': grpc.unary_unary_rpc_method_handler(
          servicer.FindOracle,
          request_deserializer=sum__pb2.ByName.FromString,
          response_serializer=sum__pb2.OracleResponse.SerializeToString,
      ),
      'DeleteOracle': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOracle,
          request_deserializer=sum__pb2.ById.FromString,
          response_serializer=sum__pb2.OracleResponse.SerializeToString,
      ),
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=sum__pb2.Call.FromString,
          response_serializer=sum__pb2.CallResponse.SerializeToString,
      ),
      'Info': grpc.unary_unary_rpc_method_handler(
          servicer.Info,
          request_deserializer=sum__pb2.Empty.FromString,
          response_serializer=sum__pb2.ServerInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sum.SumService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SumInternalServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateRecordWithId = channel.unary_unary(
        '/sum.SumInternalService/CreateRecordWithId',
        request_serializer=sum__pb2.Record.SerializeToString,
        response_deserializer=sum__pb2.RecordResponse.FromString,
        )
    self.CreateRecordsWithId = channel.unary_unary(
        '/sum.SumInternalService/CreateRecordsWithId',
        request_serializer=sum__pb2.Records.SerializeToString,
        response_deserializer=sum__pb2.RecordResponse.FromString,
        )
    self.DeleteRecords = channel.unary_unary(
        '/sum.SumInternalService/DeleteRecords',
        request_serializer=sum__pb2.RecordIds.SerializeToString,
        response_deserializer=sum__pb2.RecordResponse.FromString,
        )


class SumInternalServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateRecordWithId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateRecordsWithId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRecords(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SumInternalServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateRecordWithId': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRecordWithId,
          request_deserializer=sum__pb2.Record.FromString,
          response_serializer=sum__pb2.RecordResponse.SerializeToString,
      ),
      'CreateRecordsWithId': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRecordsWithId,
          request_deserializer=sum__pb2.Records.FromString,
          response_serializer=sum__pb2.RecordResponse.SerializeToString,
      ),
      'DeleteRecords': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRecords,
          request_deserializer=sum__pb2.RecordIds.FromString,
          response_serializer=sum__pb2.RecordResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sum.SumInternalService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SumMasterServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddNode = channel.unary_unary(
        '/sum.SumMasterService/AddNode',
        request_serializer=sum__pb2.ByAddr.SerializeToString,
        response_deserializer=sum__pb2.NodeResponse.FromString,
        )
    self.ListNodes = channel.unary_unary(
        '/sum.SumMasterService/ListNodes',
        request_serializer=sum__pb2.Empty.SerializeToString,
        response_deserializer=sum__pb2.NodeResponse.FromString,
        )
    self.DeleteNode = channel.unary_unary(
        '/sum.SumMasterService/DeleteNode',
        request_serializer=sum__pb2.ById.SerializeToString,
        response_deserializer=sum__pb2.NodeResponse.FromString,
        )


class SumMasterServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListNodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SumMasterServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddNode': grpc.unary_unary_rpc_method_handler(
          servicer.AddNode,
          request_deserializer=sum__pb2.ByAddr.FromString,
          response_serializer=sum__pb2.NodeResponse.SerializeToString,
      ),
      'ListNodes': grpc.unary_unary_rpc_method_handler(
          servicer.ListNodes,
          request_deserializer=sum__pb2.Empty.FromString,
          response_serializer=sum__pb2.NodeResponse.SerializeToString,
      ),
      'DeleteNode': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteNode,
          request_deserializer=sum__pb2.ById.FromString,
          response_serializer=sum__pb2.NodeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sum.SumMasterService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
